language: go
go:
  - tip
install:
  - go get
script:
  - wget https://github.com/traviscross/mtr/archive/v0.87.zip
  - unzip v0.87.zip
  - cd mtr-0.87
  - ./bootstrap.sh && ./configure && make
  - cp ./mtr-packet ../
  - go test